FROM node:lts-buster AS compile-image

COPY ./ui /app/ui

WORKDIR /app/ui
RUN npm install \
    && npm run build-ukr \
    && npm run build-eng \
    && rm -r ./node_modules

FROM python:3.8-slim

LABEL maintainer "Kyrylo Malakhov <malakhovks@nas.gov.ua> and Oleksandr Shchurov <alexandershchurov@gmail.com> and Tatiana Malakhova <malakhovatb@outlook.com>"
LABEL description "Vec2Read - An NLP-Powered set of services for the speed reading skills evolution in children of primary general education."

COPY ./server /docsim/server
WORKDIR /docsim/server/

RUN mkdir -p /static/ukr \
&& mkdir -p /static/eng

COPY --from=compile-image /app/ui/dist/ukr/* /docsim/server/static/ukr/
COPY --from=compile-image /app/ui/dist/ukr/index.html /docsim/server/templates/index-ukr.html
COPY --from=compile-image /app/ui/dist/eng/en/* /docsim/server/static/eng/
COPY --from=compile-image /app/ui/dist/eng/en/index.html /docsim/server/templates/index-eng.html

# Expose the port uWSGI will listen on
EXPOSE 5000

RUN apt-get -y clean \
    && apt-get -y update \
    && apt-get -y install python-dev \
    && apt-get -y install build-essential \
    && apt-get -y install unzip \
    && apt-get -y install bzip2 \
    && apt-get -y install wget \
    && apt-get -y install curl \
    # && apt-get -y install httpie \
    && pip install -r ./deploy/requirements.txt --src /usr/local/src \
    # Download models
    # && wget -O ./models/navec_hudlit_v1_12B_500K_300d_100q.bin 'https://onedrive.live.com/download?cid=6E30536EE062F9C9&resid=6E30536EE062F9C9%2175543&authkey=AOD8PeRE6LlVEiE' \
    && (cd ./models && curl -J -O "https://nextcloud.ai-service.ml/index.php/s/ePpZJHMcs76LrNw/download") \
    # && http https://nextcloud.ai-service.ml/index.php/s/ePpZJHMcs76LrNw/download/navec_hudlit_v1_12B_500K_300d_100q.bin > ./models/navec_hudlit_v1_12B_500K_300d_100q.bin \
    && wget -O ./models/fiction.lowercased.lemmatized.word2vec.300d.bz2 https://lang.org.ua/static/downloads/models/fiction.lowercased.lemmatized.word2vec.300d.bz2 \
    && bzip2 -d ./models/fiction.lowercased.lemmatized.word2vec.300d.bz2 \
    && wget -O ./models/ubercorpus.lowercased.lemmatized.word2vec.300d.bz2 https://lang.org.ua/static/downloads/models/ubercorpus.lowercased.lemmatized.word2vec.300d.bz2 \
    && bzip2 -d ./models/ubercorpus.lowercased.lemmatized.word2vec.300d.bz2 \
    && wget -O ./models/180.zip http://vectors.nlpl.eu/repository/20/180.zip \
    && unzip -j ./models/180.zip model.txt -d ./models/ruscorpora_upos_cbow_300_20_2019/ \
    && rm -r ./models/180.zip \
    && rm -r /root/.cache \
    && apt-get -y clean \
    && apt-get -y autoremove

# Finally, we run uWSGI with the ini file we
# created earlier
CMD ["uwsgi", "--ini", "./deploy/uwsgi.ini"]